spring:
  application:
    name: seckill
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seckill?&useSSL=false
    username: root
    password: root
#thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
#rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: cloud
    password: cloud
    virtual-host: /cloud
# mybatis
mybatis:
  type-aliases-package: com.andy.seckill.domain
  configuration:
    # 是否开启自动驼峰命名规则
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 600
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    lazy-loading-enabled: true
    use-generated-keys: true

#  mapper-locations: classpath:mybatis/mappers/*.xml

# 如果在application中配置后xml就不用配置了
#  config-location: classpath:mybatis/mybatis-config-xml
<<<<<<< HEAD

=======
<<<<<<< HEAD


=======
>>>>>>> 933af3379fa7a4b5f4553875814ddd7007a9bd72
>>>>>>> 6d72cfdb0fc11c0134a51558bf6bffbc88afe4cb
